[profile.default]
src         = "src"
out         = "out"
libs        = ["dependencies"]
evm_version = "cancun"
fork_cache  = true

[dependencies]
forge-std                          = { version = "1.9.4" }
solmate                            = "6.8.0"
openzeppelin-contracts-upgradeable = { version = "5.1.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", tag = "v5.1.0" }
openzeppelin-contracts             = { version = "5.1.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.1.0" }
solady                             = { version = "0.0.268", git = "https://github.com/Vectorized/solady.git", tag = "v0.0.268" }
morpho-blue                        = { version = "1.0.0", git = "https://github.com/morpho-org/morpho-blue.git", rev = "12b8a453643d5ef9d55abd88b9f8cfa866882aa5" }
aave-v3-core                       = { version = "1.19.4", git = "https://github.com/aave/aave-v3-core.git", tag = "v1.19.4" }

[soldeer]
recursive_deps = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
